apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
