apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: webapp-blue
  namespace: production
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: blue
    image: kodekloud/webapp-color
    name: webapp
    ports:
    - containerPort: 8080