apiVersion: v1
kind: Service
metadata:
  name: app-srv
  namespace: production
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - targetPort: 8080 # service port -> port
    port: 8080       # service port
    nodePort: 30008 # exposed port