apiVersion: v1
kind: Service
metadata:
  name: wordpress-np
  labels:
    name: wordpress
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      NodePort: 30090
  selector:
    app: wordpress
